version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
sphinx:
  configuration: ./bindings/python/docs/source/conf.py
conda:
  environment: ./bindings/python/docs/environment.yml
python:
  install:
    # install the package itself
    - method: pip
      path: ./bindings/python
