version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    create_environment:
        - asdf plugin add uv
        - asdf install uv latest
        - asdf global uv latest
    install:
        - cd bindings/python && uv sync --no-install-project --group docs
    build:
        html:
          - cd bindings/python && uv run --no-project sphinx-build -c docs/source -T -b html docs $READTHEDOCS_OUTPUT/html
