version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  commands:
    - NO_EXT=1 pip install ./bindings/python[docs]
    - mkdir --parents $READTHEDOCS_OUTPUT/html/
    - cd docs
    - make html
    - cp --recursive html/* $READTHEDOCS_OUTPUT/html/
