{% set name = "pymongoarrow" %}
{% set version = "0.2.0.dev0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymongoarrow-{{ version }}.tar.gz
  url: file:///d/a//mongo-arrow/mongo-arrow/bindings/python/dist/pymongoarrow-{{ version }}.tar.gz

build:
  number: 0
  script:
    - export MONGO_NO_COPY_LIBARROW=1            # [unix]
    - export MONGO_LIBARROW_DIR="${PREFIX}/lib"  # [unix]
    - export MONGO_NO_COPY_LIBBSON=1             # [unix]
    - export MONGO_LIBBSON_DIR="${PREFIX}/lib"   # [unix]
    - set MONGO_NO_COPY_LIBARROW=1               # [win]
    - set "MONGO_LIBARROW_DIR=%LIBRARY_LIB%"     # [win]
    - set MONGO_NO_COPY_LIBBSON=1                # [win]
    - set "MONGO_LIBBSON_DIR=%LIBRARY_LIB%"      # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  build:
    - python >=3.6                        
    #- cross-python_{{ target_platform }}  
    - cython >=0.29                       
    - setuptools >=47                     
    - libbson  >=1,<2                          
    - arrow-cpp  # constrained
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
   
  host:
    - python >=3.6
    - arrow-cpp
    - cython >=0.29
    - libbson >=1,<2
    - pip
    - pyarrow >=6,<6.1
    - python
    
  run:
    - {{ pin_compatible('pyarrow', max_pin='x') }}
    - pymongo >=3.11,<5
    - python >=3.6

test:
  imports:
    - pymongoarrow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pymongoarrow/
  summary: Tools for using NumPy, Pandas and PyArrow with MongoDB
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - blink1073
    - ShaneHarvey
